Event Emission from viewmodel to Event Manager and Rename Project Flow Update
tuanchauict/MonoSketch pull request #645
Opened 2024-12-28 08:04 UTC by ibretsam

**Changes Summary:**

1. Event Emission from `viewmodel.ts` to Event Manager:

     - Events are now emitted from `viewmodel.ts` to the Event Manager. Since I’m still getting familiar with the codebase, I'm not entirely sure if this is the best approach yet, but it's a start. Let me know if my implementation looks correct or if there’s a better way to handle this.

2. Rename Project Flow Update:

     - Added an `onSubmit` event to the `NoBackgroundModal`, which is now bound to the Enter key. This change allows users to submit the new project name by pressing Enter, while pressing ESC will cancel the renaming process.

     - Why do I do that? While testing the existing rename flow, I found it a bit confusing. Specifically, when the `RenameProjectModal` popped up, pressing ESC or clicking outside the modal would dismiss it, but the new project name would still be updated. Meanwhile, pressing Enter didn’t do anything at all. In most UI flows, ESC should cancel the action without making changes, and Enter should confirm it. That’s why I added the `onSubmit` method. Now, pressing Enter submits the new name and updates the project name, while ESC properly cancels without making any changes. This update should make the renaming process more intuitive and predictable.

2024-12-28 08:08 UTC, ibretsam commented on monosketch-svelte/src/lib/ui/modal/common/NoBackgroundModal.svelte
> +export let onSubmit: () => void = () => {};
I’ve initialized it as an empty function to ensure it's optional—other components using this one won’t need any changes, and everything will work as before if the function isn’t needed.

2025-01-13 06:16 UTC, tuanchauict requested changes
Let me handle this task

2025-01-13 06:16 UTC, tuanchauict commented on monosketch-svelte/src/lib/ui/modal/recent-project/viewmodel.ts
> +export const projectDataViewModel = new ProjectDataViewModel(appContext.actionManager);
This is not correct. `appContext` should be achieved from the context of Svelte.
Then we will set `projectDataViewModel` into the context for internal component used.

2025-01-13 06:16 UTC, tuanchauict commented on monosketch-svelte/src/lib/ui/modal/recent-project/viewmodel.ts
> +        this.actionManager.setOneTimeAction(OneTimeAction.ProjectAction.RenameCurrentProject(newName));
This is not correct. `setRenamingProject` means set the target project for renaming, not setting the project name. Set project name is done by `setProjectName`

2025-01-13 06:16 UTC, tuanchauict commented on monosketch-svelte/src/lib/ui/modal/common/NoBackgroundModal.svelte
> +    } else if (event.key === 'Enter') {
I don't think we should handle this key inside the modal component container. This key should be captured explicitly by the content of the modal.

2025-02-04 04:55 UTC, closed without merging